name: Assuming AWS role through OIDC
on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  awsrole:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::726824350591:role/oidc-github-actions
          role-session-name: github-actions-test
          aws-region: us-east-1