name: Copy releases to ecr public

on:
  workflow_dispatch:
    inputs:
      version:
        description: What version would you like to use

permissions:
  id-token: write
  contents: read

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/arm64,linux/amd64
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::726824350591:role/oidc-github-actions
          role-session-name: actions-push-to-ecr-public
          aws-region: us-east-1

      - name: Login to AWS ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
        env:
          AWS_DEFAULT_REGION: 'us-east-1'
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        env:
          REGISTRY: ${{ steps.login-ecr-public-outputs.registry }}
          REGISTRY_ALIAS: unleashorg
          REPOSITORY: unleash-proxy
        with:
          images: |
            ${{ steps.login-ecr-public.outputs.registry }}/unleashorg/unleash-proxy
          tags: |
            ${{ github.event.inputs.version }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}          
