# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Enable corepack
      run: corepack enable
    - name: Install npm 11.5.1
      run: npm install -g npm@11.5.1
    - run: npm --version
    - run: yarn install --immutable
      env:
        YARN_ENABLE_SCRIPTS: false
    - run: yarn fmt:check
    - run: yarn lint
    - run: yarn build
    - run: yarn test --coverage
